# Graduate Rankings Map

## Convert ranking data to html

In [1]:
# Dependencies
import csv
import pandas as pd

In [2]:
# Read the CSV file and create a dataframe
all_rankings_df= pd.read_csv('allrankingsfordisplay.csv')
all_rankings_df.head()

,Institution Name,City,State,Degree,Rank,Latitude,Longitude
0,Yale University,New Haven,CT,Law,1,41.311166,-72.926689
1,Stanford University,Stanford,CA,Law,2,37.429537,-122.164447
2,Harvard University,Cambridge,MA,Law,3,42.374480,-71.118314
3,University of Chicago,Chicago,IL,Law,4,41.789178,-87.601202
4,Columbia University in the City of New York,New York,NY,Law,5,40.808294,-73.961886

In [4]:
# Remove the unnecessary index
all_rankings=all_rankings_df.set_index('Institution Name')
all_rankings

,City,State,Degree,Rank,Latitude,Longitude
Institution Name,,,,,,
Yale University,New Haven,CT,Law,1,41.311166,-72.926689
Stanford University,Stanford,CA,Law,2,37.429537,-122.164447
Harvard University,Cambridge,MA,Law,3,42.374480,-71.118314
University of Chicago,Chicago,IL,Law,4,41.789178,-87.601202
Columbia University in the City of New York,New York,NY,Law,5,40.808294,-73.961886
New York University,New York,NY,Law,6,40.729460,-73.997265
University of Pennsylvania,Philadelphia,PA,Law,7,39.950937,-75.193912
University of Virginia-Main Campus,Charlottesville,VA,Law,8,38.035673,-78.503431
University of Michigan-Ann Arbor,Ann Arbor,MI,Law,9,42.275929,-83.742774
Duke University,Durham,NC,Law,10,36.001142,-78.937627
Northwestern University,Evanston,IL,Law,10,42.050364,-87.679864
University of California-Berkeley,Berkeley,CA,Law,10,37.871923,-122.260476
Cornell University,Ithaca,NY,Law,13,42.447208,-76.483086
Georgetown University,Washington,DC,Law,14,38.908817,-77.073465
University of California-Los Angeles,Los Angeles,CA,Law,15,34.068897,-118.443913
The University of Texas at Austin,Austin,TX,Law,16,30.286095,-97.739299
University of Southern California,Los Angeles,CA,Law,17,34.021286,-118.284181
Vanderbilt University,Nashville,TN,Law,18,36.146597,-86.803374
Washington University in St Louis,Saint Louis,MO,Law,18,38.647936,-90.310610
University of Minnesota-Twin Cities,Minneapolis,MN,Law,20,44.977894,-93.235360
University of Pennsylvania,Philadelphia,PA,Business,1,39.950937,-75.193912
Stanford University,Stanford,CA,Business,2,37.429537,-122.164447
Harvard University,Cambridge,MA,Business,3,42.374480,-71.118314
Massachusetts Institute of Technology,Cambridge,MA,Business,3,42.360104,-71.092116
University of Chicago,Chicago,IL,Business,3,41.789178,-87.601202
Columbia University in the City of New York,New York,NY,Business,6,40.808294,-73.961886
Northwestern University,Evanston,IL,Business,6,42.050364,-87.679864
University of California-Berkeley,Berkeley,CA,Business,6,37.871923,-122.260476
Yale University,New Haven,CT,Business,9,41.311166,-72.926689
Duke University,Durham,NC,Business,10,36.001142,-78.937627
...,...,...,...,...,...,...
Cornell University,Ithaca,NY,Mathematics,13,42.447208,-76.483086
The University of Texas at Austin,Austin,TX,Mathematics,14,30.286095,-97.739299
Brown University,Providence,RI,Mathematics,14,41.826179,-71.403851
University of Pennsylvania,Philadelphia,PA,Mathematics,16,39.950937,-75.193912
Duke University,Durham,NC,Mathematics,16,36.001142,-78.937627
University of Wisconsin-Madison,Madison,WI,Mathematics,16,43.073866,-89.405362
University of California-San Diego,La Jolla,CA,Mathematics,19,32.876603,-117.237805
University of Illinois at Urbana-Champaign,Champaign,IL,Mathematics,19,40.108872,-88.230315
University of Minnesota-Twin Cities,Minneapolis,MN,Mathematics,19,44.977894,-93.235360
Massachusetts Institute of Technology,Cambridge,MA,Physics,1,42.360104,-71.092116
Stanford University,Stanford,CA,Physics,1,37.429537,-122.164447
California Institute of Technology,Pasadena,CA,Physics,3,34.139280,-118.125752
Princeton University,Princeton,NJ,Physics,3,40.348740,-74.659367
Harvard University,Cambridge,MA,Physics,3,42.374480,-71.118314
University of California-Berkeley,Berkeley,CA,Physics,3,37.871923,-122.260476
Cornell University,Ithaca,NY,Physics,7,42.447208,-76.483086
University of Chicago,Chicago,IL,Physics,7,41.789178,-87.601202
University of Illinois at Urbana-Champaign,Champaign,IL,Physics,9,40.108872,-88.230315
University of California-Santa Barbara,Santa Barbara,CA,Physics,10,34.416302,-119.846439
Columbia University in the City of New York,New York,NY,Physics,10,40.808294,-73.961886
Yale University,New Haven,CT,Physics,12,41.311166,-72.926689
University of Michigan-Ann Arbor,Ann Arbor,MI,Physics,13,42.275929,-83.742774
University of Maryland-College Park,College Park,MD,Physics,14,38.988186,-76.944723
University of Colorado Boulder,Boulder,CO,Physics,14,40.008787,-105.270833
University of Pennsylvania,Philadelphia,PA,Physics,14,39.950937,-75.193912
Johns Hopkins University,Baltimore,MD,Physics,17,39.328985,-76.621597
University of California-San Diego,La Jolla,CA,Physics,17,32.876603,-117.237805
University of California-Los Angeles,Los Angeles,CA,Physics,17,34.068897,-118.443913
The University of Texas at Austin,Austin,TX,Physics,17,30.286095,-97.739299
University of Wisconsin-Madison,Madison,WI,Physics,17,43.073866,-89.405362

In [5]:
# Convert the pandas dataframe to html and export as "dow_jones_html_data.html"
all_rankings.to_html('all_rankings.html')