In [1]:
from bs4 import BeautifulSoup
from splinter.browser import Browser
import requests
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [4]:
#Law

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-law-schools/law-rankings/"
browser.visit(url1)

time.sleep(80)

cities = []
rankNumber = []
universityName = []

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('div', attrs = {'class' : 's85n6m5-0-Box-cwadsP dlYdgX'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 bstttc'})
    target2 = i.find('div', class_='ranked RankList__Rank-qghlf4-2 hSEzjh')
    target3 = i.find('a', class_='Anchor-s1mkgztv-0 gPdGYK')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota']

In [5]:
#Business

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-business-schools/mba-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('div', attrs = {'class' : 's85n6m5-0-Box-cwadsP dlYdgX'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 bstttc'})
    target2 = i.find('div', class_='ranked RankList__Rank-qghlf4-2 hSEzjh')
    target3 = i.find('a', class_='Anchor-s1mkgztv-0 gPdGYK')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)']

In [6]:
#Education

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-education-schools/edu-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('div', attrs = {'class' : 's85n6m5-0-Box-cwadsP dlYdgX'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 bstttc'})
    target2 = i.find('div', class_='ranked RankList__Rank-qghlf4-2 hSEzjh')
    target3 = i.find('a', class_='Anchor-s1mkgztv-0 gPdGYK')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX', 'Cambridge, MA', 'Philadelphia, PA', 'Stanford, CA', 'Los Angeles, CA', 'Madison, WI', 'Nashville, TN', 'Baltimore, MD', 'New York, NY', 'New York, NY', 'Evanston, IL', 'Ann Arbor, MI', 'Los Angeles, CA', 'Austin, TX', 'Eugene, OR', 'Seattle, WA', 'Phoenix, AZ', 'VA', 'Berkeley, CA', 'Lawrence, KS', 'Richmond, VA']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19', '#1', '#2', '#3', '#3', '#3', '#6', '#7', '#7', '#7', '#10', '#11', '#12', '#13', '#14', '#14', '#16', '#17', '#18', '#18', '#20']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)', 'Harvard University', 'University of Pennsylvania', 'Stanford University', 'University of California--Los Angeles', 'University of Wisconsin--Madison', 'Vanderbilt University (Peabody)', 'Johns Hopkins University', 'New York University (Steinhardt)', 'Teachers College, Columbia University', 'Northwestern University', 'University of Michigan--Ann Arbor', 'University of Southern California (Rossier)', 'University of Texas--Austin', 'University of Oregon', 'University of Washington', 'Arizona State University', 'University of Virginia (Curry)', 'University of California--Berkeley', 'University of Kansas', 'Virginia Commonwealth University']

In [8]:
#Engineering

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-engineering-schools/eng-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('div', attrs = {'class' : 's85n6m5-0-Box-cwadsP dlYdgX'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 bstttc'})
    target2 = i.find('div', class_='ranked RankList__Rank-qghlf4-2 hSEzjh')
    target3 = i.find('a', class_='Anchor-s1mkgztv-0 gPdGYK')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX', 'Cambridge, MA', 'Philadelphia, PA', 'Stanford, CA', 'Los Angeles, CA', 'Madison, WI', 'Nashville, TN', 'Baltimore, MD', 'New York, NY', 'New York, NY', 'Evanston, IL', 'Ann Arbor, MI', 'Los Angeles, CA', 'Austin, TX', 'Eugene, OR', 'Seattle, WA', 'Phoenix, AZ', 'VA', 'Berkeley, CA', 'Lawrence, KS', 'Richmond, VA', 'Cambridge, MA', 'Stanford, CA', 'Berkeley, CA', 'Pittsburgh, PA', 'Pasadena, CA', 'Ann Arbor, MI', 'Atlanta, GA', 'West Lafayette, IN', 'Los Angeles, CA', 'Urbana, IL', 'New York, NY', 'La Jolla, CA', 'Austin, TX', 'Ithaca, NY', 'College Station, TX', 'Los Angeles, CA', 'Baltimore, MD', 'Princeton, NJ', 'Philadelphia, PA', 'Evanston, IL']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19', '#1', '#2', '#3', '#3', '#3', '#6', '#7', '#7', '#7', '#10', '#11', '#12', '#13', '#14', '#14', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#4', '#5', '#5', '#7', '#8', '#9', '#10', '#11', '#11', '#11', '#14', '#15', '#16', '#17', '#17', '#17', '#20']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)', 'Harvard University', 'University of Pennsylvania', 'Stanford University', 'University of California--Los Angeles', 'University of Wisconsin--Madison', 'Vanderbilt University (Peabody)', 'Johns Hopkins University', 'New York University (Steinhardt)', 'Teachers College, Columbia University', 'Northwestern University', 'University of Michigan--Ann Arbor', 'University of Southern California (Rossier)', 'University of Texas--Austin', 'University of Oregon', 'University of Washington', 'Arizona State University', 'University of Virginia (Curry)', 'University of California--Berkeley', 'University of Kansas', 'Virginia Commonwealth University', 'Massachusetts Institute of Technology', 'Stanford University', 'University of California--Berkeley', 'Carnegie Mellon University', 'California Institute of Technology', 'University of Michigan--Ann Arbor', 'Georgia Institute of Technology', 'Purdue University--West Lafayette', 'University of Southern California (Viterbi)', 'University of Illinois--Urbana-Champaign', 'Columbia University (Fu Foundation)', 'University of California--San Diego (Jacobs)', 'University of Texas--Austin (Cockrell)', 'Cornell University', 'Texas A&M University--College Station', 'University of California--Los Angeles (Samueli)', 'Johns Hopkins University (Whiting)', 'Princeton University', 'University of Pennsylvania', 'Northwestern University (McCormick)']

In [11]:
#Medicine

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-medical-schools/primary-care-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('div', attrs = {'class' : 's85n6m5-0-Box-cwadsP dlYdgX'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 bstttc'})
    target2 = i.find('div', class_='ranked RankList__Rank-qghlf4-2 hSEzjh')
    target3 = i.find('a', class_='Anchor-s1mkgztv-0 gPdGYK')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX', 'Cambridge, MA', 'Philadelphia, PA', 'Stanford, CA', 'Los Angeles, CA', 'Madison, WI', 'Nashville, TN', 'Baltimore, MD', 'New York, NY', 'New York, NY', 'Evanston, IL', 'Ann Arbor, MI', 'Los Angeles, CA', 'Austin, TX', 'Eugene, OR', 'Seattle, WA', 'Phoenix, AZ', 'VA', 'Berkeley, CA', 'Lawrence, KS', 'Richmond, VA', 'Cambridge, MA', 'Stanford, CA', 'Berkeley, CA', 'Pittsburgh, PA', 'Pasadena, CA', 'Ann Arbor, MI', 'Atlanta, GA', 'West Lafayette, IN', 'Los Angeles, CA', 'Urbana, IL', 'New York, NY', 'La Jolla, CA', 'Austin, TX', 'Ithaca, NY', 'College Station, TX', 'Los Angeles, CA', 'Baltimore, MD', 'Princeton, NJ', 'Philadelphia, PA', 'Evanston, IL', 'Chapel Hill, NC', 'Seattle, WA', 'San Francisco, CA', 'Houston, TX', 'Los Angeles, CA', 'Portland, OR', 'Ann Arbor, MI', 'Omaha, NE', 'Sacramento, CA', 'Minneapolis, MN', 'Philadelphia, PA', 'Aurora, CO', 'St. Louis, MO', 'Pittsburgh, PA', 'Worcester, MA', 'Madison, WI', 'Boston, MA', 'Hanover, NH', 'Chicago, IL', 'Dallas, TX']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19', '#1', '#2', '#3', '#3', '#3', '#6', '#7', '#7', '#7', '#10', '#11', '#12', '#13', '#14', '#14', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#4', '#5', '#5', '#7', '#8', '#9', '#10', '#11', '#11', '#11', '#14', '#15', '#16', '#17', '#17', '#17', '#20', '#1', '#2', '#3', '#4', '#5', '#6', '#6', '#8', '#9', '#10', '#10', '#12', '#12', '#14', '#15', '#16', '#17', '#18', '#18', '#18']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)', 'Harvard University', 'University of Pennsylvania', 'Stanford University', 'University of California--Los Angeles', 'University of Wisconsin--Madison', 'Vanderbilt University (Peabody)', 'Johns Hopkins University', 'New York University (Steinhardt)', 'Teachers College, Columbia University', 'Northwestern University', 'University of Michigan--Ann Arbor', 'University of Southern California (Rossier)', 'University of Texas--Austin', 'University of Oregon', 'University of Washington', 'Arizona State University', 'University of Virginia (Curry)', 'University of California--Berkeley', 'University of Kansas', 'Virginia Commonwealth University', 'Massachusetts Institute of Technology', 'Stanford University', 'University of California--Berkeley', 'Carnegie Mellon University', 'California Institute of Technology', 'University of Michigan--Ann Arbor', 'Georgia Institute of Technology', 'Purdue University--West Lafayette', 'University of Southern California (Viterbi)', 'University of Illinois--Urbana-Champaign', 'Columbia University (Fu Foundation)', 'University of California--San Diego (Jacobs)', 'University of Texas--Austin (Cockrell)', 'Cornell University', 'Texas A&M University--College Station', 'University of California--Los Angeles (Samueli)', 'Johns Hopkins University (Whiting)', 'Princeton University', 'University of Pennsylvania', 'Northwestern University (McCormick)', 'University of North Carolina--Chapel Hill', 'University of Washington', 'University of California--San Francisco', 'Baylor College of Medicine', 'University of California--Los Angeles (Geffen)', 'Oregon Health and Science University', 'University of Michigan--Ann Arbor', 'University of Nebraska Medical Center', 'University of California--Davis', 'University of Minnesota', 'University of Pennsylvania (Perelman)', 'University of Colorado', 'Washington University in St. Louis', 'University of Pittsburgh', 'University of Massachusetts--Worcester', 'University of Wisconsin--Madison', 'Harvard University', 'Dartmouth College (Geisel)', 'University of Chicago (Pritzker)', 'University of Texas Southwestern Medical Center']

In [12]:
#Nursing

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-nursing-schools/nur-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('div', attrs = {'class' : 's85n6m5-0-Box-cwadsP dlYdgX'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 bstttc'})
    target2 = i.find('div', class_='ranked RankList__Rank-qghlf4-2 hSEzjh')
    target3 = i.find('a', class_='Anchor-s1mkgztv-0 gPdGYK')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX', 'Cambridge, MA', 'Philadelphia, PA', 'Stanford, CA', 'Los Angeles, CA', 'Madison, WI', 'Nashville, TN', 'Baltimore, MD', 'New York, NY', 'New York, NY', 'Evanston, IL', 'Ann Arbor, MI', 'Los Angeles, CA', 'Austin, TX', 'Eugene, OR', 'Seattle, WA', 'Phoenix, AZ', 'VA', 'Berkeley, CA', 'Lawrence, KS', 'Richmond, VA', 'Cambridge, MA', 'Stanford, CA', 'Berkeley, CA', 'Pittsburgh, PA', 'Pasadena, CA', 'Ann Arbor, MI', 'Atlanta, GA', 'West Lafayette, IN', 'Los Angeles, CA', 'Urbana, IL', 'New York, NY', 'La Jolla, CA', 'Austin, TX', 'Ithaca, NY', 'College Station, TX', 'Los Angeles, CA', 'Baltimore, MD', 'Princeton, NJ', 'Philadelphia, PA', 'Evanston, IL', 'Chapel Hill, NC', 'Seattle, WA', 'San Francisco, CA', 'Houston, TX', 'Los Angeles, CA', 'Portland, OR', 'Ann Arbor, MI', 'Omaha, NE', 'Sacramento, CA', 'Minneapolis, MN', 'Philadelphia, PA', 'Aurora, CO', 'St. Louis, MO', 'Pittsburgh, PA', 'Worcester, MA', 'Madison, WI', 'Boston, MA', 'Hanover, NH', 'Chicago, IL', 'Dallas, TX', 'Baltimore, MD', 'Durham, NC', 'Philadelphia, PA', 'Atlanta, GA', 'New York, NY', 'Chapel Hill, NC', 'New Haven, CT', 'Columbus, OH', 'Chicago, IL', 'Ann Arbor, MI', 'Nashville, TN', 'New York, NY', 'Baltimore, MD', 'Pittsburgh, PA', 'Seattle, WA', 'Cleveland, OH', 'Chicago, IL', 'Birmingham, AL', 'San Francisco, CA', 'Los Angeles, CA']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19', '#1', '#2', '#3', '#3', '#3', '#6', '#7', '#7', '#7', '#10', '#11', '#12', '#13', '#14', '#14', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#4', '#5', '#5', '#7', '#8', '#9', '#10', '#11', '#11', '#11', '#14', '#15', '#16', '#17', '#17', '#17', '#20', '#1', '#2', '#3', '#4', '#5', '#6', '#6', '#8', '#9', '#10', '#10', '#12', '#12', '#14', '#15', '#16', '#17', '#18', '#18', '#18', '#1', '#2', '#3', '#4', '#5', '#5', '#5', '#8', '#8', '#8', '#8', '#12', '#12', '#12', '#12', '#16', '#16', '#18', '#18', '#20']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)', 'Harvard University', 'University of Pennsylvania', 'Stanford University', 'University of California--Los Angeles', 'University of Wisconsin--Madison', 'Vanderbilt University (Peabody)', 'Johns Hopkins University', 'New York University (Steinhardt)', 'Teachers College, Columbia University', 'Northwestern University', 'University of Michigan--Ann Arbor', 'University of Southern California (Rossier)', 'University of Texas--Austin', 'University of Oregon', 'University of Washington', 'Arizona State University', 'University of Virginia (Curry)', 'University of California--Berkeley', 'University of Kansas', 'Virginia Commonwealth University', 'Massachusetts Institute of Technology', 'Stanford University', 'University of California--Berkeley', 'Carnegie Mellon University', 'California Institute of Technology', 'University of Michigan--Ann Arbor', 'Georgia Institute of Technology', 'Purdue University--West Lafayette', 'University of Southern California (Viterbi)', 'University of Illinois--Urbana-Champaign', 'Columbia University (Fu Foundation)', 'University of California--San Diego (Jacobs)', 'University of Texas--Austin (Cockrell)', 'Cornell University', 'Texas A&M University--College Station', 'University of California--Los Angeles (Samueli)', 'Johns Hopkins University (Whiting)', 'Princeton University', 'University of Pennsylvania', 'Northwestern University (McCormick)', 'University of North Carolina--Chapel Hill', 'University of Washington', 'University of California--San Francisco', 'Baylor College of Medicine', 'University of California--Los Angeles (Geffen)', 'Oregon Health and Science University', 'University of Michigan--Ann Arbor', 'University of Nebraska Medical Center', 'University of California--Davis', 'University of Minnesota', 'University of Pennsylvania (Perelman)', 'University of Colorado', 'Washington University in St. Louis', 'University of Pittsburgh', 'University of Massachusetts--Worcester', 'University of Wisconsin--Madison', 'Harvard University', 'Dartmouth College (Geisel)', 'University of Chicago (Pritzker)', 'University of Texas Southwestern Medical Center', 'Johns Hopkins University', 'Duke University', 'University of Pennsylvania', 'Emory University', 'Columbia University', 'University of North Carolina--Chapel Hill', 'Yale University', 'Ohio State University', 'Rush University', 'University of Michigan--Ann Arbor', 'Vanderbilt University', 'New York University (Meyers)', 'University of Maryland--Baltimore', 'University of Pittsburgh', 'University of Washington', 'Case Western Reserve University', 'University of Illinois--Chicago', 'University of Alabama--Birmingham', 'University of California--San Francisco', 'University of California--Los Angeles']

In [13]:
#Fine Arts
executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-fine-arts-schools/fine-arts-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX', 'Cambridge, MA', 'Philadelphia, PA', 'Stanford, CA', 'Los Angeles, CA', 'Madison, WI', 'Nashville, TN', 'Baltimore, MD', 'New York, NY', 'New York, NY', 'Evanston, IL', 'Ann Arbor, MI', 'Los Angeles, CA', 'Austin, TX', 'Eugene, OR', 'Seattle, WA', 'Phoenix, AZ', 'VA', 'Berkeley, CA', 'Lawrence, KS', 'Richmond, VA', 'Cambridge, MA', 'Stanford, CA', 'Berkeley, CA', 'Pittsburgh, PA', 'Pasadena, CA', 'Ann Arbor, MI', 'Atlanta, GA', 'West Lafayette, IN', 'Los Angeles, CA', 'Urbana, IL', 'New York, NY', 'La Jolla, CA', 'Austin, TX', 'Ithaca, NY', 'College Station, TX', 'Los Angeles, CA', 'Baltimore, MD', 'Princeton, NJ', 'Philadelphia, PA', 'Evanston, IL', 'Chapel Hill, NC', 'Seattle, WA', 'San Francisco, CA', 'Houston, TX', 'Los Angeles, CA', 'Portland, OR', 'Ann Arbor, MI', 'Omaha, NE', 'Sacramento, CA', 'Minneapolis, MN', 'Philadelphia, PA', 'Aurora, CO', 'St. Louis, MO', 'Pittsburgh, PA', 'Worcester, MA', 'Madison, WI', 'Boston, MA', 'Hanover, NH', 'Chicago, IL', 'Dallas, TX', 'Baltimore, MD', 'Durham, NC', 'Philadelphia, PA', 'Atlanta, GA', 'New York, NY', 'Chapel Hill, NC', 'New Haven, CT', 'Columbus, OH', 'Chicago, IL', 'Ann Arbor, MI', 'Nashville, TN', 'New York, NY', 'Baltimore, MD', 'Pittsburgh, PA', 'Seattle, WA', 'Cleveland, OH', 'Chicago, IL', 'Birmingham, AL', 'San Francisco, CA', 'Los Angeles, CA', 'New Haven, CT', 'Richmond, VA', 'Chicago, IL', 'New York, NY', 'Alfred, NY', 'Baltimore, MD', 'Annandale-on-Hudson, NY', 'San Francisco, CA', 'Stanford, CA', 'Madison, WI', 'Los Angeles, CA', 'Providence, RI', 'Pittsburgh , PA', 'Bloomfield Hills, MI', 'Valencia, CA', 'Saint Louis, MO', 'La Jolla, CA', 'Brooklyn, NY', 'Philadelphia, PA', 'Tempe, AZ']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19', '#1', '#2', '#3', '#3', '#3', '#6', '#7', '#7', '#7', '#10', '#11', '#12', '#13', '#14', '#14', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#4', '#5', '#5', '#7', '#8', '#9', '#10', '#11', '#11', '#11', '#14', '#15', '#16', '#17', '#17', '#17', '#20', '#1', '#2', '#3', '#4', '#5', '#6', '#6', '#8', '#9', '#10', '#10', '#12', '#12', '#14', '#15', '#16', '#17', '#18', '#18', '#18', '#1', '#2', '#3', '#4', '#5', '#5', '#5', '#8', '#8', '#8', '#8', '#12', '#12', '#12', '#12', '#16', '#16', '#18', '#18', '#20', '#1 ', '#2 ', '#4 ', '#6 ', '#9 ', '#9 ', '#13 ', '#15 ', '#15 ', '#15 ', '#2 ', '#4 ', '#6 ', '#6 ', '#9 ', '#12 ', '#13 ', '#15 ', '#15 ', '#20 ']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)', 'Harvard University', 'University of Pennsylvania', 'Stanford University', 'University of California--Los Angeles', 'University of Wisconsin--Madison', 'Vanderbilt University (Peabody)', 'Johns Hopkins University', 'New York University (Steinhardt)', 'Teachers College, Columbia University', 'Northwestern University', 'University of Michigan--Ann Arbor', 'University of Southern California (Rossier)', 'University of Texas--Austin', 'University of Oregon', 'University of Washington', 'Arizona State University', 'University of Virginia (Curry)', 'University of California--Berkeley', 'University of Kansas', 'Virginia Commonwealth University', 'Massachusetts Institute of Technology', 'Stanford University', 'University of California--Berkeley', 'Carnegie Mellon University', 'California Institute of Technology', 'University of Michigan--Ann Arbor', 'Georgia Institute of Technology', 'Purdue University--West Lafayette', 'University of Southern California (Viterbi)', 'University of Illinois--Urbana-Champaign', 'Columbia University (Fu Foundation)', 'University of California--San Diego (Jacobs)', 'University of Texas--Austin (Cockrell)', 'Cornell University', 'Texas A&M University--College Station', 'University of California--Los Angeles (Samueli)', 'Johns Hopkins University (Whiting)', 'Princeton University', 'University of Pennsylvania', 'Northwestern University (McCormick)', 'University of North Carolina--Chapel Hill', 'University of Washington', 'University of California--San Francisco', 'Baylor College of Medicine', 'University of California--Los Angeles (Geffen)', 'Oregon Health and Science University', 'University of Michigan--Ann Arbor', 'University of Nebraska Medical Center', 'University of California--Davis', 'University of Minnesota', 'University of Pennsylvania (Perelman)', 'University of Colorado', 'Washington University in St. Louis', 'University of Pittsburgh', 'University of Massachusetts--Worcester', 'University of Wisconsin--Madison', 'Harvard University', 'Dartmouth College (Geisel)', 'University of Chicago (Pritzker)', 'University of Texas Southwestern Medical Center', 'Johns Hopkins University', 'Duke University', 'University of Pennsylvania', 'Emory University', 'Columbia University', 'University of North Carolina--Chapel Hill', 'Yale University', 'Ohio State University', 'Rush University', 'University of Michigan--Ann Arbor', 'Vanderbilt University', 'New York University (Meyers)', 'University of Maryland--Baltimore', 'University of Pittsburgh', 'University of Washington', 'Case Western Reserve University', 'University of Illinois--Chicago', 'University of Alabama--Birmingham', 'University of California--San Francisco', 'University of California--Los Angeles', 'Yale University', 'Virginia Commonwealth University', 'School of the Art Institute of Chicago', 'Columbia University', 'Alfred University--New York State College of Ceramics', 'Maryland Institute College of Art', 'Bard College', 'California College of the Arts', 'Stanford University', 'University of Wisconsin--Madison', 'University of California--Los Angeles', 'Rhode Island School of Design', 'Carnegie Mellon University', 'Cranbrook Academy of Art', 'California Institute of the Arts', 'Washington University in St. Louis', 'University of California--San Diego', 'Pratt Institute', 'Temple University', 'Arizona State University']

In [14]:
#Library
executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-library-information-science-programs/library-information-science-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX', 'Cambridge, MA', 'Philadelphia, PA', 'Stanford, CA', 'Los Angeles, CA', 'Madison, WI', 'Nashville, TN', 'Baltimore, MD', 'New York, NY', 'New York, NY', 'Evanston, IL', 'Ann Arbor, MI', 'Los Angeles, CA', 'Austin, TX', 'Eugene, OR', 'Seattle, WA', 'Phoenix, AZ', 'VA', 'Berkeley, CA', 'Lawrence, KS', 'Richmond, VA', 'Cambridge, MA', 'Stanford, CA', 'Berkeley, CA', 'Pittsburgh, PA', 'Pasadena, CA', 'Ann Arbor, MI', 'Atlanta, GA', 'West Lafayette, IN', 'Los Angeles, CA', 'Urbana, IL', 'New York, NY', 'La Jolla, CA', 'Austin, TX', 'Ithaca, NY', 'College Station, TX', 'Los Angeles, CA', 'Baltimore, MD', 'Princeton, NJ', 'Philadelphia, PA', 'Evanston, IL', 'Chapel Hill, NC', 'Seattle, WA', 'San Francisco, CA', 'Houston, TX', 'Los Angeles, CA', 'Portland, OR', 'Ann Arbor, MI', 'Omaha, NE', 'Sacramento, CA', 'Minneapolis, MN', 'Philadelphia, PA', 'Aurora, CO', 'St. Louis, MO', 'Pittsburgh, PA', 'Worcester, MA', 'Madison, WI', 'Boston, MA', 'Hanover, NH', 'Chicago, IL', 'Dallas, TX', 'Baltimore, MD', 'Durham, NC', 'Philadelphia, PA', 'Atlanta, GA', 'New York, NY', 'Chapel Hill, NC', 'New Haven, CT', 'Columbus, OH', 'Chicago, IL', 'Ann Arbor, MI', 'Nashville, TN', 'New York, NY', 'Baltimore, MD', 'Pittsburgh, PA', 'Seattle, WA', 'Cleveland, OH', 'Chicago, IL', 'Birmingham, AL', 'San Francisco, CA', 'Los Angeles, CA', 'New Haven, CT', 'Richmond, VA', 'Chicago, IL', 'New York, NY', 'Alfred, NY', 'Baltimore, MD', 'Annandale-on-Hudson, NY', 'San Francisco, CA', 'Stanford, CA', 'Madison, WI', 'Los Angeles, CA', 'Providence, RI', 'Pittsburgh , PA', 'Bloomfield Hills, MI', 'Valencia, CA', 'Saint Louis, MO', 'La Jolla, CA', 'Brooklyn, NY', 'Philadelphia, PA', 'Tempe, AZ', 'Champaign, IL', 'Chapel Hill, NC', 'Ann Arbor, MI', 'New Brunswick, NJ', 'Bloomington, IN', 'Philadelphia, PA', 'Boston, MA', 'Madison, WI', 'Knoxville, TN', 'Kent, OH', 'Seattle, WA', 'Syracuse, NY', 'Austin, TX', 'College Park, MD', 'Pittsburgh, PA', 'Tallahassee, FL', 'Los Angeles, CA', 'Milwaukee, WI', 'Columbia, SC', 'Lexington, KY']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19', '#1', '#2', '#3', '#3', '#3', '#6', '#7', '#7', '#7', '#10', '#11', '#12', '#13', '#14', '#14', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#4', '#5', '#5', '#7', '#8', '#9', '#10', '#11', '#11', '#11', '#14', '#15', '#16', '#17', '#17', '#17', '#20', '#1', '#2', '#3', '#4', '#5', '#6', '#6', '#8', '#9', '#10', '#10', '#12', '#12', '#14', '#15', '#16', '#17', '#18', '#18', '#18', '#1', '#2', '#3', '#4', '#5', '#5', '#5', '#8', '#8', '#8', '#8', '#12', '#12', '#12', '#12', '#16', '#16', '#18', '#18', '#20', '#1 ', '#2 ', '#4 ', '#6 ', '#9 ', '#9 ', '#13 ', '#15 ', '#15 ', '#15 ', '#2 ', '#4 ', '#6 ', '#6 ', '#9 ', '#12 ', '#13 ', '#15 ', '#15 ', '#20 ', '#1 ', '#3 ', '#5 ', '#7 ', '#9 ', '#11 ', '#12 ', '#14 ', '#17 ', '#19 ', '#2 ', '#4 ', '#5 ', '#8 ', '#10 ', '#12 ', '#14 ', '#14 ', '#18 ', '#20 ']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)', 'Harvard University', 'University of Pennsylvania', 'Stanford University', 'University of California--Los Angeles', 'University of Wisconsin--Madison', 'Vanderbilt University (Peabody)', 'Johns Hopkins University', 'New York University (Steinhardt)', 'Teachers College, Columbia University', 'Northwestern University', 'University of Michigan--Ann Arbor', 'University of Southern California (Rossier)', 'University of Texas--Austin', 'University of Oregon', 'University of Washington', 'Arizona State University', 'University of Virginia (Curry)', 'University of California--Berkeley', 'University of Kansas', 'Virginia Commonwealth University', 'Massachusetts Institute of Technology', 'Stanford University', 'University of California--Berkeley', 'Carnegie Mellon University', 'California Institute of Technology', 'University of Michigan--Ann Arbor', 'Georgia Institute of Technology', 'Purdue University--West Lafayette', 'University of Southern California (Viterbi)', 'University of Illinois--Urbana-Champaign', 'Columbia University (Fu Foundation)', 'University of California--San Diego (Jacobs)', 'University of Texas--Austin (Cockrell)', 'Cornell University', 'Texas A&M University--College Station', 'University of California--Los Angeles (Samueli)', 'Johns Hopkins University (Whiting)', 'Princeton University', 'University of Pennsylvania', 'Northwestern University (McCormick)', 'University of North Carolina--Chapel Hill', 'University of Washington', 'University of California--San Francisco', 'Baylor College of Medicine', 'University of California--Los Angeles (Geffen)', 'Oregon Health and Science University', 'University of Michigan--Ann Arbor', 'University of Nebraska Medical Center', 'University of California--Davis', 'University of Minnesota', 'University of Pennsylvania (Perelman)', 'University of Colorado', 'Washington University in St. Louis', 'University of Pittsburgh', 'University of Massachusetts--Worcester', 'University of Wisconsin--Madison', 'Harvard University', 'Dartmouth College (Geisel)', 'University of Chicago (Pritzker)', 'University of Texas Southwestern Medical Center', 'Johns Hopkins University', 'Duke University', 'University of Pennsylvania', 'Emory University', 'Columbia University', 'University of North Carolina--Chapel Hill', 'Yale University', 'Ohio State University', 'Rush University', 'University of Michigan--Ann Arbor', 'Vanderbilt University', 'New York University (Meyers)', 'University of Maryland--Baltimore', 'University of Pittsburgh', 'University of Washington', 'Case Western Reserve University', 'University of Illinois--Chicago', 'University of Alabama--Birmingham', 'University of California--San Francisco', 'University of California--Los Angeles', 'Yale University', 'Virginia Commonwealth University', 'School of the Art Institute of Chicago', 'Columbia University', 'Alfred University--New York State College of Ceramics', 'Maryland Institute College of Art', 'Bard College', 'California College of the Arts', 'Stanford University', 'University of Wisconsin--Madison', 'University of California--Los Angeles', 'Rhode Island School of Design', 'Carnegie Mellon University', 'Cranbrook Academy of Art', 'California Institute of the Arts', 'Washington University in St. Louis', 'University of California--San Diego', 'Pratt Institute', 'Temple University', 'Arizona State University', 'University of Illinois--Urbana-Champaign', 'University of North Carolina--Chapel Hill', 'University of Michigan--Ann Arbor', 'Rutgers, The State University of New Jersey--New Brunswick', 'Indiana University--Bloomington', 'Drexel University', 'Simmons College', 'University of Wisconsin--Madison', 'University of Tennessee--Knoxville', 'Kent State University', 'University of Washington', 'Syracuse University', 'University of Texas--Austin', 'University of Maryland--College Park', 'University of Pittsburgh', 'Florida State University', 'University of California--Los Angeles', 'University of Wisconsin--Milwaukee', 'University of South Carolina', 'University of Kentucky']

In [15]:
#Public Affairs
executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-public-affairs-schools/public-affairs-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['New Haven, CT', 'Stanford, CA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'New York, NY', 'Philadelphia, PA', 'Charlottesville, VA', 'Ann Arbor, MI', 'Durham, NC', 'Chicago, IL', 'Berkeley, CA', 'Ithaca, NY', 'Washington, DC', 'Los Angeles, CA', 'Austin, TX', 'Los Angeles, CA', 'Nashville, TN', 'St. Louis, MO', 'Minneapolis, MN', 'Philadelphia, PA', 'Stanford, CA', 'Boston, MA', 'Cambridge, MA', 'Chicago, IL', 'New York, NY', 'Evanston, IL', 'Berkeley, CA', 'New Haven, CT', 'Durham, NC', 'Ann Arbor, MI', 'Hanover, NH', 'New York, NY', 'Charlottesville, VA', 'Ithaca, NY', 'Los Angeles, CA', 'Pittsburgh, PA', 'Los Angeles, CA', 'Chapel Hill, NC', 'Austin, TX', 'Cambridge, MA', 'Philadelphia, PA', 'Stanford, CA', 'Los Angeles, CA', 'Madison, WI', 'Nashville, TN', 'Baltimore, MD', 'New York, NY', 'New York, NY', 'Evanston, IL', 'Ann Arbor, MI', 'Los Angeles, CA', 'Austin, TX', 'Eugene, OR', 'Seattle, WA', 'Phoenix, AZ', 'VA', 'Berkeley, CA', 'Lawrence, KS', 'Richmond, VA', 'Cambridge, MA', 'Stanford, CA', 'Berkeley, CA', 'Pittsburgh, PA', 'Pasadena, CA', 'Ann Arbor, MI', 'Atlanta, GA', 'West Lafayette, IN', 'Los Angeles, CA', 'Urbana, IL', 'New York, NY', 'La Jolla, CA', 'Austin, TX', 'Ithaca, NY', 'College Station, TX', 'Los Angeles, CA', 'Baltimore, MD', 'Princeton, NJ', 'Philadelphia, PA', 'Evanston, IL', 'Chapel Hill, NC', 'Seattle, WA', 'San Francisco, CA', 'Houston, TX', 'Los Angeles, CA', 'Portland, OR', 'Ann Arbor, MI', 'Omaha, NE', 'Sacramento, CA', 'Minneapolis, MN', 'Philadelphia, PA', 'Aurora, CO', 'St. Louis, MO', 'Pittsburgh, PA', 'Worcester, MA', 'Madison, WI', 'Boston, MA', 'Hanover, NH', 'Chicago, IL', 'Dallas, TX', 'Baltimore, MD', 'Durham, NC', 'Philadelphia, PA', 'Atlanta, GA', 'New York, NY', 'Chapel Hill, NC', 'New Haven, CT', 'Columbus, OH', 'Chicago, IL', 'Ann Arbor, MI', 'Nashville, TN', 'New York, NY', 'Baltimore, MD', 'Pittsburgh, PA', 'Seattle, WA', 'Cleveland, OH', 'Chicago, IL', 'Birmingham, AL', 'San Francisco, CA', 'Los Angeles, CA', 'New Haven, CT', 'Richmond, VA', 'Chicago, IL', 'New York, NY', 'Alfred, NY', 'Baltimore, MD', 'Annandale-on-Hudson, NY', 'San Francisco, CA', 'Stanford, CA', 'Madison, WI', 'Los Angeles, CA', 'Providence, RI', 'Pittsburgh , PA', 'Bloomfield Hills, MI', 'Valencia, CA', 'Saint Louis, MO', 'La Jolla, CA', 'Brooklyn, NY', 'Philadelphia, PA', 'Tempe, AZ', 'Champaign, IL', 'Chapel Hill, NC', 'Ann Arbor, MI', 'New Brunswick, NJ', 'Bloomington, IN', 'Philadelphia, PA', 'Boston, MA', 'Madison, WI', 'Knoxville, TN', 'Kent, OH', 'Seattle, WA', 'Syracuse, NY', 'Austin, TX', 'College Park, MD', 'Pittsburgh, PA', 'Tallahassee, FL', 'Los Angeles, CA', 'Milwaukee, WI', 'Columbia, SC', 'Lexington, KY', 'Bloomington, IN', 'Cambridge, MA', 'Athens, GA', 'New York, NY', 'Ann Arbor, MI', 'Chicago, IL', 'Austin, TX', 'Phoenix, AZ', 'Washington, DC', 'Los Angeles, CA', 'Syracuse, NY', 'Los Angeles, CA', 'Seattle, WA', 'Berkeley, CA', 'Princeton, NJ', 'Minneapolis, MN', 'Washington, DC', 'Pittsburgh, PA', 'Columbus, OH', 'Lawrence, KS']
['#1', '#2', '#3', '#4', '#5', '#6', '#7', '#8', '#9', '#10', '#10', '#10', '#13', '#14', '#15', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#3', '#3', '#6', '#6', '#6', '#9', '#10', '#10', '#12', '#12', '#12', '#15', '#16', '#17', '#17', '#19', '#19', '#1', '#2', '#3', '#3', '#3', '#6', '#7', '#7', '#7', '#10', '#11', '#12', '#13', '#14', '#14', '#16', '#17', '#18', '#18', '#20', '#1', '#2', '#3', '#4', '#5', '#5', '#7', '#8', '#9', '#10', '#11', '#11', '#11', '#14', '#15', '#16', '#17', '#17', '#17', '#20', '#1', '#2', '#3', '#4', '#5', '#6', '#6', '#8', '#9', '#10', '#10', '#12', '#12', '#14', '#15', '#16', '#17', '#18', '#18', '#18', '#1', '#2', '#3', '#4', '#5', '#5', '#5', '#8', '#8', '#8', '#8', '#12', '#12', '#12', '#12', '#16', '#16', '#18', '#18', '#20', '#1 ', '#2 ', '#4 ', '#6 ', '#9 ', '#9 ', '#13 ', '#15 ', '#15 ', '#15 ', '#2 ', '#4 ', '#6 ', '#6 ', '#9 ', '#12 ', '#13 ', '#15 ', '#15 ', '#20 ', '#1 ', '#3 ', '#5 ', '#7 ', '#9 ', '#11 ', '#12 ', '#14 ', '#17 ', '#19 ', '#2 ', '#4 ', '#5 ', '#8 ', '#10 ', '#12 ', '#14 ', '#14 ', '#18 ', '#20 ', '#1 ', '#3 ', '#5 ', '#7 ', '#7 ', '#10 ', '#10 ', '#14 ', '#14 ', '#14 ', '#1 ', '#3 ', '#5 ', '#7 ', '#10 ', '#10 ', '#14 ', '#14 ', '#14 ', '#14 ']
['Yale University', 'Stanford University', 'Harvard University', 'University of Chicago', 'Columbia University', 'New York University', 'University of Pennsylvania', 'University of Virginia', 'University of Michigan--Ann Arbor', 'Duke University', 'Northwestern University (Pritzker)', 'University of California--Berkeley', 'Cornell University', 'Georgetown University', 'University of California--Los Angeles', 'University of Texas--Austin', 'University of Southern California (Gould)', 'Vanderbilt University', 'Washington University in St. Louis', 'University of Minnesota', 'University of Pennsylvania (Wharton)', 'Stanford University', 'Harvard University', 'Massachusetts Institute of Technology (Sloan)', 'University of Chicago (Booth)', 'Columbia University', 'Northwestern University (Kellogg)', 'University of California--Berkeley (Haas)', 'Yale University', 'Duke University (Fuqua)', 'University of Michigan--Ann Arbor (Ross)', 'Dartmouth College (Tuck)', 'New York University (Stern)', 'University of Virginia (Darden)', 'Cornell University (Johnson)', 'University of California--Los Angeles (Anderson)', 'Carnegie Mellon University (Tepper)', 'University of Southern California (Marshall)', 'University of North Carolina--Chapel Hill (Kenan-Flagler)', 'University of Texas--Austin (McCombs)', 'Harvard University', 'University of Pennsylvania', 'Stanford University', 'University of California--Los Angeles', 'University of Wisconsin--Madison', 'Vanderbilt University (Peabody)', 'Johns Hopkins University', 'New York University (Steinhardt)', 'Teachers College, Columbia University', 'Northwestern University', 'University of Michigan--Ann Arbor', 'University of Southern California (Rossier)', 'University of Texas--Austin', 'University of Oregon', 'University of Washington', 'Arizona State University', 'University of Virginia (Curry)', 'University of California--Berkeley', 'University of Kansas', 'Virginia Commonwealth University', 'Massachusetts Institute of Technology', 'Stanford University', 'University of California--Berkeley', 'Carnegie Mellon University', 'California Institute of Technology', 'University of Michigan--Ann Arbor', 'Georgia Institute of Technology', 'Purdue University--West Lafayette', 'University of Southern California (Viterbi)', 'University of Illinois--Urbana-Champaign', 'Columbia University (Fu Foundation)', 'University of California--San Diego (Jacobs)', 'University of Texas--Austin (Cockrell)', 'Cornell University', 'Texas A&M University--College Station', 'University of California--Los Angeles (Samueli)', 'Johns Hopkins University (Whiting)', 'Princeton University', 'University of Pennsylvania', 'Northwestern University (McCormick)', 'University of North Carolina--Chapel Hill', 'University of Washington', 'University of California--San Francisco', 'Baylor College of Medicine', 'University of California--Los Angeles (Geffen)', 'Oregon Health and Science University', 'University of Michigan--Ann Arbor', 'University of Nebraska Medical Center', 'University of California--Davis', 'University of Minnesota', 'University of Pennsylvania (Perelman)', 'University of Colorado', 'Washington University in St. Louis', 'University of Pittsburgh', 'University of Massachusetts--Worcester', 'University of Wisconsin--Madison', 'Harvard University', 'Dartmouth College (Geisel)', 'University of Chicago (Pritzker)', 'University of Texas Southwestern Medical Center', 'Johns Hopkins University', 'Duke University', 'University of Pennsylvania', 'Emory University', 'Columbia University', 'University of North Carolina--Chapel Hill', 'Yale University', 'Ohio State University', 'Rush University', 'University of Michigan--Ann Arbor', 'Vanderbilt University', 'New York University (Meyers)', 'University of Maryland--Baltimore', 'University of Pittsburgh', 'University of Washington', 'Case Western Reserve University', 'University of Illinois--Chicago', 'University of Alabama--Birmingham', 'University of California--San Francisco', 'University of California--Los Angeles', 'Yale University', 'Virginia Commonwealth University', 'School of the Art Institute of Chicago', 'Columbia University', 'Alfred University--New York State College of Ceramics', 'Maryland Institute College of Art', 'Bard College', 'California College of the Arts', 'Stanford University', 'University of Wisconsin--Madison', 'University of California--Los Angeles', 'Rhode Island School of Design', 'Carnegie Mellon University', 'Cranbrook Academy of Art', 'California Institute of the Arts', 'Washington University in St. Louis', 'University of California--San Diego', 'Pratt Institute', 'Temple University', 'Arizona State University', 'University of Illinois--Urbana-Champaign', 'University of North Carolina--Chapel Hill', 'University of Michigan--Ann Arbor', 'Rutgers, The State University of New Jersey--New Brunswick', 'Indiana University--Bloomington', 'Drexel University', 'Simmons College', 'University of Wisconsin--Madison', 'University of Tennessee--Knoxville', 'Kent State University', 'University of Washington', 'Syracuse University', 'University of Texas--Austin', 'University of Maryland--College Park', 'University of Pittsburgh', 'Florida State University', 'University of California--Los Angeles', 'University of Wisconsin--Milwaukee', 'University of South Carolina', 'University of Kentucky', "Indiana University--Bloomington (O'Neill)", 'Harvard University', 'University of Georgia', 'New York University', 'University of Michigan--Ann Arbor', 'University of Chicago', 'University of Texas--Austin', 'Arizona State University', 'George Washington University', 'University of California--Los Angeles', 'Syracuse University', 'University of Southern California', 'University of Washington', 'University of California--Berkeley', 'Princeton University', 'University of Minnesota--Twin Cities', 'American University', 'Carnegie Mellon University', 'Ohio State University', 'University of Kansas']

In [23]:
names = ('INSTNM', 'firstcity', 'Degree', 'Rank')
data = pd.DataFrame(columns = names)
data

Empty DataFrame
Columns: [INSTNM, firstcity, Degree, Rank]
Index: []

In [24]:
degrees = []

for i in range (20):
    degrees.append('Law')

for i in range (20):
    degrees.append('Business')
    
for i in range (20):
    degrees.append('Education')

for i in range (20):
    degrees.append('Engineering')
    
for i in range (20):
    degrees.append('Medicine')

for i in range (20):
    degrees.append('Nursing')
    
for i in range (20):
    degrees.append('Fine Arts')

for i in range (20):
    degrees.append('Library and Information Studies')
    
for i in range (20):
    degrees.append('Public Affairs')
    
degrees

['Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Law',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Business',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Education',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Engineering',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Medicine',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Nursing',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Fine Arts',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Library and Information Studies',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs',
 'Public Affairs']

In [26]:
data['INSTNM'] = universityName
data['firstcity'] = cities
data['Degree'] = degrees
data['Rank'] = rankNumber

data.head()

                  INSTNM      firstcity Degree Rank
0        Yale University  New Haven, CT    Law   #1
1    Stanford University   Stanford, CA    Law   #2
2     Harvard University  Cambridge, MA    Law   #3
3  University of Chicago    Chicago, IL    Law   #4
4    Columbia University   New York, NY    Law   #5

In [30]:
data['Rank'] = data['Rank'].apply(str).replace('#', '', regex=True)

data.head()

                  INSTNM      firstcity Degree Rank
0        Yale University  New Haven, CT    Law    1
1    Stanford University   Stanford, CA    Law    2
2     Harvard University  Cambridge, MA    Law    3
3  University of Chicago    Chicago, IL    Law    4
4    Columbia University   New York, NY    Law    5

In [46]:
data['CITY'] = data.firstcity.str.split(', ').str[0]
data['STATE'] = data.firstcity.str.split(', ').str[-1]

data

,INSTNM,firstcity,CITY,Degree,Rank,STATE,S
0,Yale University,"New Haven, CT",New Haven,Law,1,CT,CT
1,Stanford University,"Stanford, CA",Stanford,Law,2,CA,CA
2,Harvard University,"Cambridge, MA",Cambridge,Law,3,MA,MA
3,University of Chicago,"Chicago, IL",Chicago,Law,4,IL,IL
4,Columbia University,"New York, NY",New York,Law,5,NY,NY
...,...,...,...,...,...,...,...
175,University of Minnesota--Twin Cities,"Minneapolis, MN",Minneapolis,Public Affairs,10,MN,MN
176,American University,"Washington, DC",Washington,Public Affairs,14,DC,DC
177,Carnegie Mellon University,"Pittsburgh, PA",Pittsburgh,Public Affairs,14,PA,PA
178,Ohio State University,"Columbus, OH",Columbus,Public Affairs,14,OH,OH
179,University of Kansas,"Lawrence, KS",Lawrence,Public Affairs,14,KS,KS

In [48]:
data.to_csv(r'C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\Brute-Force-Grad-College-Rankings-Map\UniversityRankData.csv')