In [1]:
from bs4 import BeautifulSoup
from splinter.browser import Browser
import requests
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

In [4]:
#Biological Sciences

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-science-schools/biological-sciences-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0

cities = []
rankNumber = []
universityName = []


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['Cambridge, MA', 'Berkeley, CA', 'Boston, MA', 'Princeton, NJ', 'New Haven, CT', 'Durham, NC', 'New York, NY', 'St. Louis, MO', 'La Jolla, CA', 'Davis, CA', 'Stanford, CA', 'Pasadena, CA', 'Baltimore, MD', 'San Francisco, CA', 'Ithaca, NY', 'La Jolla, CA', 'Chicago, IL', 'Cold Spring Harbor, NY', 'New York, NY', 'Los Angeles, CA']
['#1 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#13 ', '#13 ', '#16 ', '#18 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#10 ', '#13 ', '#16 ', '#18 ', '#18 ']
['Massachusetts Institute of Technology', 'University of California--Berkeley', 'Harvard University', 'Princeton University', 'Yale University', 'Duke University', 'Rockefeller University', 'Washington University in St. Louis', 'University of California--San Diego', 'University of California--Davis', 'Stanford University', 'California Institute of Technology', 'Johns Hopkins University', 'University of California--San Francisco', 'Cornell University', 'The Scripps Research Institute', 'University of Chicago', 'Cold Spring Harbor Laboratory', 'Columbia University', 'University of California--Los Angeles']

In [5]:
#Chemistry

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-science-schools/chemistry-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0

for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['Cambridge, MA', 'Berkeley, CA', 'Boston, MA', 'Princeton, NJ', 'New Haven, CT', 'Durham, NC', 'New York, NY', 'St. Louis, MO', 'La Jolla, CA', 'Davis, CA', 'Stanford, CA', 'Pasadena, CA', 'Baltimore, MD', 'San Francisco, CA', 'Ithaca, NY', 'La Jolla, CA', 'Chicago, IL', 'Cold Spring Harbor, NY', 'New York, NY', 'Los Angeles, CA', 'Pasadena, CA', 'Cambridge, MA', 'Berkeley, CA', 'La Jolla, CA', 'New York, NY', 'Princeton, NJ', 'New Haven, CT', 'Los Angeles, CA', 'Chapel Hill, NC', 'Philadelphia, PA', 'Cambridge, MA', 'Stanford, CA', 'Evanston, IL', 'Urbana, IL', 'Ithaca, NY', 'Madison, WI', 'Chicago, IL', 'Ann Arbor, MI', 'Austin, TX', 'Atlanta, GA']
['#1 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#13 ', '#13 ', '#16 ', '#18 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#10 ', '#13 ', '#16 ', '#18 ', '#18 ', '#1 ', '#2 ', '#2 ', '#6 ', '#9 ', '#9 ', '#9 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#6 ', '#6 ', '#9 ', '#9 ', '#14 ', '#15 ', '#15 ', '#20 ']
['Massachusetts Institute of Technology', 'University of California--Berkeley', 'Harvard University', 'Princeton University', 'Yale University', 'Duke University', 'Rockefeller University', 'Washington University in St. Louis', 'University of California--San Diego', 'University of California--Davis', 'Stanford University', 'California Institute of Technology', 'Johns Hopkins University', 'University of California--San Francisco', 'Cornell University', 'The Scripps Research Institute', 'University of Chicago', 'Cold Spring Harbor Laboratory', 'Columbia University', 'University of California--Los Angeles', 'California Institute of Technology', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'The Scripps Research Institute', 'Columbia University', 'Princeton University', 'Yale University', 'University of California--Los Angeles', 'University of North Carolina--Chapel Hill', 'University of Pennsylvania', 'Harvard University', 'Stanford University', 'Northwestern University', 'University of Illinois--Urbana-Champaign', 'Cornell University', 'University of Wisconsin--Madison', 'University of Chicago', 'University of Michigan--Ann Arbor', 'University of Texas--Austin', 'Georgia Institute of Technology']

In [6]:
#Computer Science

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-science-schools/computer-science-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['Cambridge, MA', 'Berkeley, CA', 'Boston, MA', 'Princeton, NJ', 'New Haven, CT', 'Durham, NC', 'New York, NY', 'St. Louis, MO', 'La Jolla, CA', 'Davis, CA', 'Stanford, CA', 'Pasadena, CA', 'Baltimore, MD', 'San Francisco, CA', 'Ithaca, NY', 'La Jolla, CA', 'Chicago, IL', 'Cold Spring Harbor, NY', 'New York, NY', 'Los Angeles, CA', 'Pasadena, CA', 'Cambridge, MA', 'Berkeley, CA', 'La Jolla, CA', 'New York, NY', 'Princeton, NJ', 'New Haven, CT', 'Los Angeles, CA', 'Chapel Hill, NC', 'Philadelphia, PA', 'Cambridge, MA', 'Stanford, CA', 'Evanston, IL', 'Urbana, IL', 'Ithaca, NY', 'Madison, WI', 'Chicago, IL', 'Ann Arbor, MI', 'Austin, TX', 'Atlanta, GA', 'Pittsburgh, PA', 'Stanford, CA', 'Urbana, IL', 'Seattle, WA', 'Princeton, NJ', 'Pasadena, CA', 'New York, NY', 'Madison, WI', 'La Jolla, CA', 'Philadelphia, PA', 'Cambridge, MA', 'Berkeley, CA', 'Ithaca, NY', 'Atlanta, GA', 'Austin, TX', 'Ann Arbor, MI', 'Los Angeles, CA', 'Cambridge, MA', 'College Park, MD', 'West Lafayette, IN']
['#1 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#13 ', '#13 ', '#16 ', '#18 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#10 ', '#13 ', '#16 ', '#18 ', '#18 ', '#1 ', '#2 ', '#2 ', '#6 ', '#9 ', '#9 ', '#9 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#6 ', '#6 ', '#9 ', '#9 ', '#14 ', '#15 ', '#15 ', '#20 ', '#1 ', '#1 ', '#5 ', '#6 ', '#8 ', '#11 ', '#13 ', '#13 ', '#16 ', '#19 ', '#1 ', '#1 ', '#6 ', '#8 ', '#10 ', '#11 ', '#13 ', '#16 ', '#16 ', '#20 ']
['Massachusetts Institute of Technology', 'University of California--Berkeley', 'Harvard University', 'Princeton University', 'Yale University', 'Duke University', 'Rockefeller University', 'Washington University in St. Louis', 'University of California--San Diego', 'University of California--Davis', 'Stanford University', 'California Institute of Technology', 'Johns Hopkins University', 'University of California--San Francisco', 'Cornell University', 'The Scripps Research Institute', 'University of Chicago', 'Cold Spring Harbor Laboratory', 'Columbia University', 'University of California--Los Angeles', 'California Institute of Technology', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'The Scripps Research Institute', 'Columbia University', 'Princeton University', 'Yale University', 'University of California--Los Angeles', 'University of North Carolina--Chapel Hill', 'University of Pennsylvania', 'Harvard University', 'Stanford University', 'Northwestern University', 'University of Illinois--Urbana-Champaign', 'Cornell University', 'University of Wisconsin--Madison', 'University of Chicago', 'University of Michigan--Ann Arbor', 'University of Texas--Austin', 'Georgia Institute of Technology', 'Carnegie Mellon University', 'Stanford University', 'University of Illinois--Urbana-Champaign', 'University of Washington', 'Princeton University', 'California Institute of Technology', 'Columbia University', 'University of Wisconsin--Madison', 'University of California--San Diego', 'University of Pennsylvania', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Cornell University', 'Georgia Institute of Technology', 'University of Texas--Austin', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Harvard University', 'University of Maryland--College Park', 'Purdue University--West Lafayette']

In [7]:
#Earth Sciences

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-science-schools/earth-sciences-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0

for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['Cambridge, MA', 'Berkeley, CA', 'Boston, MA', 'Princeton, NJ', 'New Haven, CT', 'Durham, NC', 'New York, NY', 'St. Louis, MO', 'La Jolla, CA', 'Davis, CA', 'Stanford, CA', 'Pasadena, CA', 'Baltimore, MD', 'San Francisco, CA', 'Ithaca, NY', 'La Jolla, CA', 'Chicago, IL', 'Cold Spring Harbor, NY', 'New York, NY', 'Los Angeles, CA', 'Pasadena, CA', 'Cambridge, MA', 'Berkeley, CA', 'La Jolla, CA', 'New York, NY', 'Princeton, NJ', 'New Haven, CT', 'Los Angeles, CA', 'Chapel Hill, NC', 'Philadelphia, PA', 'Cambridge, MA', 'Stanford, CA', 'Evanston, IL', 'Urbana, IL', 'Ithaca, NY', 'Madison, WI', 'Chicago, IL', 'Ann Arbor, MI', 'Austin, TX', 'Atlanta, GA', 'Pittsburgh, PA', 'Stanford, CA', 'Urbana, IL', 'Seattle, WA', 'Princeton, NJ', 'Pasadena, CA', 'New York, NY', 'Madison, WI', 'La Jolla, CA', 'Philadelphia, PA', 'Cambridge, MA', 'Berkeley, CA', 'Ithaca, NY', 'Atlanta, GA', 'Austin, TX', 'Ann Arbor, MI', 'Los Angeles, CA', 'Cambridge, MA', 'College Park, MD', 'West Lafayette, IN', 'Pasadena, CA', 'Stanford, CA', 'Palisades, NY', 'Austin, TX', 'Tucson, AZ', 'Ann Arbor, MI', 'Los Angeles, CA', 'Tempe, AZ', 'La Jolla, CA', 'Ithaca, NY', 'Cambridge, MA', 'Berkeley, CA', 'University Park, PA', 'Cambridge, MA', 'Princeton, NJ', 'Seattle, WA', 'New Haven, CT', 'Providence, RI', 'Madison, WI', 'Santa Barbara, CA']
['#1 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#13 ', '#13 ', '#16 ', '#18 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#10 ', '#13 ', '#16 ', '#18 ', '#18 ', '#1 ', '#2 ', '#2 ', '#6 ', '#9 ', '#9 ', '#9 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#6 ', '#6 ', '#9 ', '#9 ', '#14 ', '#15 ', '#15 ', '#20 ', '#1 ', '#1 ', '#5 ', '#6 ', '#8 ', '#11 ', '#13 ', '#13 ', '#16 ', '#19 ', '#1 ', '#1 ', '#6 ', '#8 ', '#10 ', '#11 ', '#13 ', '#16 ', '#16 ', '#20 ', '#1 ', '#2 ', '#5 ', '#7 ', '#8 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#5 ', '#8 ', '#10 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ']
['Massachusetts Institute of Technology', 'University of California--Berkeley', 'Harvard University', 'Princeton University', 'Yale University', 'Duke University', 'Rockefeller University', 'Washington University in St. Louis', 'University of California--San Diego', 'University of California--Davis', 'Stanford University', 'California Institute of Technology', 'Johns Hopkins University', 'University of California--San Francisco', 'Cornell University', 'The Scripps Research Institute', 'University of Chicago', 'Cold Spring Harbor Laboratory', 'Columbia University', 'University of California--Los Angeles', 'California Institute of Technology', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'The Scripps Research Institute', 'Columbia University', 'Princeton University', 'Yale University', 'University of California--Los Angeles', 'University of North Carolina--Chapel Hill', 'University of Pennsylvania', 'Harvard University', 'Stanford University', 'Northwestern University', 'University of Illinois--Urbana-Champaign', 'Cornell University', 'University of Wisconsin--Madison', 'University of Chicago', 'University of Michigan--Ann Arbor', 'University of Texas--Austin', 'Georgia Institute of Technology', 'Carnegie Mellon University', 'Stanford University', 'University of Illinois--Urbana-Champaign', 'University of Washington', 'Princeton University', 'California Institute of Technology', 'Columbia University', 'University of Wisconsin--Madison', 'University of California--San Diego', 'University of Pennsylvania', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Cornell University', 'Georgia Institute of Technology', 'University of Texas--Austin', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Harvard University', 'University of Maryland--College Park', 'Purdue University--West Lafayette', 'California Institute of Technology', 'Stanford University', 'Columbia University', 'University of Texas--Austin', 'University of Arizona', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Arizona State University', 'University of California--San Diego', 'Cornell University', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Pennsylvania State University--University Park', 'Harvard University', 'Princeton University', 'University of Washington', 'Yale University', 'Brown University', 'University of Wisconsin--Madison', 'University of California--Santa Barbara']

In [8]:
#Mathematics

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-science-schools/mathematics-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['Cambridge, MA', 'Berkeley, CA', 'Boston, MA', 'Princeton, NJ', 'New Haven, CT', 'Durham, NC', 'New York, NY', 'St. Louis, MO', 'La Jolla, CA', 'Davis, CA', 'Stanford, CA', 'Pasadena, CA', 'Baltimore, MD', 'San Francisco, CA', 'Ithaca, NY', 'La Jolla, CA', 'Chicago, IL', 'Cold Spring Harbor, NY', 'New York, NY', 'Los Angeles, CA', 'Pasadena, CA', 'Cambridge, MA', 'Berkeley, CA', 'La Jolla, CA', 'New York, NY', 'Princeton, NJ', 'New Haven, CT', 'Los Angeles, CA', 'Chapel Hill, NC', 'Philadelphia, PA', 'Cambridge, MA', 'Stanford, CA', 'Evanston, IL', 'Urbana, IL', 'Ithaca, NY', 'Madison, WI', 'Chicago, IL', 'Ann Arbor, MI', 'Austin, TX', 'Atlanta, GA', 'Pittsburgh, PA', 'Stanford, CA', 'Urbana, IL', 'Seattle, WA', 'Princeton, NJ', 'Pasadena, CA', 'New York, NY', 'Madison, WI', 'La Jolla, CA', 'Philadelphia, PA', 'Cambridge, MA', 'Berkeley, CA', 'Ithaca, NY', 'Atlanta, GA', 'Austin, TX', 'Ann Arbor, MI', 'Los Angeles, CA', 'Cambridge, MA', 'College Park, MD', 'West Lafayette, IN', 'Pasadena, CA', 'Stanford, CA', 'Palisades, NY', 'Austin, TX', 'Tucson, AZ', 'Ann Arbor, MI', 'Los Angeles, CA', 'Tempe, AZ', 'La Jolla, CA', 'Ithaca, NY', 'Cambridge, MA', 'Berkeley, CA', 'University Park, PA', 'Cambridge, MA', 'Princeton, NJ', 'Seattle, WA', 'New Haven, CT', 'Providence, RI', 'Madison, WI', 'Santa Barbara, CA', 'Princeton, NJ', 'Cambridge, MA', 'Berkeley, CA', 'New York, NY', 'Pasadena, CA', 'New Haven, CT', 'Ithaca, NY', 'Austin, TX', 'Philadelphia, PA', 'La Jolla, CA', 'Cambridge, MA', 'Stanford, CA', 'Chicago, IL', 'Los Angeles, CA', 'New York, NY', 'Ann Arbor, MI', 'Providence, RI', 'Durham, NC', 'Madison, WI', 'Urbana, IL']
['#1 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#13 ', '#13 ', '#16 ', '#18 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#10 ', '#13 ', '#16 ', '#18 ', '#18 ', '#1 ', '#2 ', '#2 ', '#6 ', '#9 ', '#9 ', '#9 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#6 ', '#6 ', '#9 ', '#9 ', '#14 ', '#15 ', '#15 ', '#20 ', '#1 ', '#1 ', '#5 ', '#6 ', '#8 ', '#11 ', '#13 ', '#13 ', '#16 ', '#19 ', '#1 ', '#1 ', '#6 ', '#8 ', '#10 ', '#11 ', '#13 ', '#16 ', '#16 ', '#20 ', '#1 ', '#2 ', '#5 ', '#7 ', '#8 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#5 ', '#8 ', '#10 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ', '#1 ', '#2 ', '#2 ', '#7 ', '#9 ', '#9 ', '#13 ', '#14 ', '#16 ', '#19 ', '#2 ', '#2 ', '#6 ', '#7 ', '#9 ', '#12 ', '#14 ', '#16 ', '#16 ', '#19 ']
['Massachusetts Institute of Technology', 'University of California--Berkeley', 'Harvard University', 'Princeton University', 'Yale University', 'Duke University', 'Rockefeller University', 'Washington University in St. Louis', 'University of California--San Diego', 'University of California--Davis', 'Stanford University', 'California Institute of Technology', 'Johns Hopkins University', 'University of California--San Francisco', 'Cornell University', 'The Scripps Research Institute', 'University of Chicago', 'Cold Spring Harbor Laboratory', 'Columbia University', 'University of California--Los Angeles', 'California Institute of Technology', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'The Scripps Research Institute', 'Columbia University', 'Princeton University', 'Yale University', 'University of California--Los Angeles', 'University of North Carolina--Chapel Hill', 'University of Pennsylvania', 'Harvard University', 'Stanford University', 'Northwestern University', 'University of Illinois--Urbana-Champaign', 'Cornell University', 'University of Wisconsin--Madison', 'University of Chicago', 'University of Michigan--Ann Arbor', 'University of Texas--Austin', 'Georgia Institute of Technology', 'Carnegie Mellon University', 'Stanford University', 'University of Illinois--Urbana-Champaign', 'University of Washington', 'Princeton University', 'California Institute of Technology', 'Columbia University', 'University of Wisconsin--Madison', 'University of California--San Diego', 'University of Pennsylvania', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Cornell University', 'Georgia Institute of Technology', 'University of Texas--Austin', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Harvard University', 'University of Maryland--College Park', 'Purdue University--West Lafayette', 'California Institute of Technology', 'Stanford University', 'Columbia University', 'University of Texas--Austin', 'University of Arizona', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Arizona State University', 'University of California--San Diego', 'Cornell University', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Pennsylvania State University--University Park', 'Harvard University', 'Princeton University', 'University of Washington', 'Yale University', 'Brown University', 'University of Wisconsin--Madison', 'University of California--Santa Barbara', 'Princeton University', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Columbia University', 'California Institute of Technology', 'Yale University', 'Cornell University', 'University of Texas--Austin', 'University of Pennsylvania', 'University of California--San Diego', 'Harvard University', 'Stanford University', 'University of Chicago', 'University of California--Los Angeles', 'New York University', 'University of Michigan--Ann Arbor', 'Brown University', 'Duke University', 'University of Wisconsin--Madison', 'University of Illinois--Urbana-Champaign']

In [9]:
#Physics

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-science-schools/physics-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['Cambridge, MA', 'Berkeley, CA', 'Boston, MA', 'Princeton, NJ', 'New Haven, CT', 'Durham, NC', 'New York, NY', 'St. Louis, MO', 'La Jolla, CA', 'Davis, CA', 'Stanford, CA', 'Pasadena, CA', 'Baltimore, MD', 'San Francisco, CA', 'Ithaca, NY', 'La Jolla, CA', 'Chicago, IL', 'Cold Spring Harbor, NY', 'New York, NY', 'Los Angeles, CA', 'Pasadena, CA', 'Cambridge, MA', 'Berkeley, CA', 'La Jolla, CA', 'New York, NY', 'Princeton, NJ', 'New Haven, CT', 'Los Angeles, CA', 'Chapel Hill, NC', 'Philadelphia, PA', 'Cambridge, MA', 'Stanford, CA', 'Evanston, IL', 'Urbana, IL', 'Ithaca, NY', 'Madison, WI', 'Chicago, IL', 'Ann Arbor, MI', 'Austin, TX', 'Atlanta, GA', 'Pittsburgh, PA', 'Stanford, CA', 'Urbana, IL', 'Seattle, WA', 'Princeton, NJ', 'Pasadena, CA', 'New York, NY', 'Madison, WI', 'La Jolla, CA', 'Philadelphia, PA', 'Cambridge, MA', 'Berkeley, CA', 'Ithaca, NY', 'Atlanta, GA', 'Austin, TX', 'Ann Arbor, MI', 'Los Angeles, CA', 'Cambridge, MA', 'College Park, MD', 'West Lafayette, IN', 'Pasadena, CA', 'Stanford, CA', 'Palisades, NY', 'Austin, TX', 'Tucson, AZ', 'Ann Arbor, MI', 'Los Angeles, CA', 'Tempe, AZ', 'La Jolla, CA', 'Ithaca, NY', 'Cambridge, MA', 'Berkeley, CA', 'University Park, PA', 'Cambridge, MA', 'Princeton, NJ', 'Seattle, WA', 'New Haven, CT', 'Providence, RI', 'Madison, WI', 'Santa Barbara, CA', 'Princeton, NJ', 'Cambridge, MA', 'Berkeley, CA', 'New York, NY', 'Pasadena, CA', 'New Haven, CT', 'Ithaca, NY', 'Austin, TX', 'Philadelphia, PA', 'La Jolla, CA', 'Cambridge, MA', 'Stanford, CA', 'Chicago, IL', 'Los Angeles, CA', 'New York, NY', 'Ann Arbor, MI', 'Providence, RI', 'Durham, NC', 'Madison, WI', 'Urbana, IL', 'Cambridge, MA', 'Pasadena, CA', 'Princeton, NJ', 'Ithaca, NY', 'Urbana, IL', 'Santa Barbara, CA', 'Ann Arbor, MI', 'College Park, MD', 'Baltimore, MD', 'La Jolla, CA', 'Stanford, CA', 'Cambridge, MA', 'Berkeley, CA', 'Chicago, IL', 'New York, NY', 'New Haven, CT', 'Boulder, CO', 'Philadelphia, PA', 'Los Angeles, CA', 'Austin, TX']
['#1 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#13 ', '#13 ', '#16 ', '#18 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#10 ', '#13 ', '#16 ', '#18 ', '#18 ', '#1 ', '#2 ', '#2 ', '#6 ', '#9 ', '#9 ', '#9 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#6 ', '#6 ', '#9 ', '#9 ', '#14 ', '#15 ', '#15 ', '#20 ', '#1 ', '#1 ', '#5 ', '#6 ', '#8 ', '#11 ', '#13 ', '#13 ', '#16 ', '#19 ', '#1 ', '#1 ', '#6 ', '#8 ', '#10 ', '#11 ', '#13 ', '#16 ', '#16 ', '#20 ', '#1 ', '#2 ', '#5 ', '#7 ', '#8 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#5 ', '#8 ', '#10 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ', '#1 ', '#2 ', '#2 ', '#7 ', '#9 ', '#9 ', '#13 ', '#14 ', '#16 ', '#19 ', '#2 ', '#2 ', '#6 ', '#7 ', '#9 ', '#12 ', '#14 ', '#16 ', '#16 ', '#19 ', '#1 ', '#3 ', '#3 ', '#7 ', '#9 ', '#10 ', '#13 ', '#14 ', '#17 ', '#17 ', '#1 ', '#3 ', '#3 ', '#7 ', '#10 ', '#12 ', '#14 ', '#14 ', '#17 ', '#17 ']
['Massachusetts Institute of Technology', 'University of California--Berkeley', 'Harvard University', 'Princeton University', 'Yale University', 'Duke University', 'Rockefeller University', 'Washington University in St. Louis', 'University of California--San Diego', 'University of California--Davis', 'Stanford University', 'California Institute of Technology', 'Johns Hopkins University', 'University of California--San Francisco', 'Cornell University', 'The Scripps Research Institute', 'University of Chicago', 'Cold Spring Harbor Laboratory', 'Columbia University', 'University of California--Los Angeles', 'California Institute of Technology', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'The Scripps Research Institute', 'Columbia University', 'Princeton University', 'Yale University', 'University of California--Los Angeles', 'University of North Carolina--Chapel Hill', 'University of Pennsylvania', 'Harvard University', 'Stanford University', 'Northwestern University', 'University of Illinois--Urbana-Champaign', 'Cornell University', 'University of Wisconsin--Madison', 'University of Chicago', 'University of Michigan--Ann Arbor', 'University of Texas--Austin', 'Georgia Institute of Technology', 'Carnegie Mellon University', 'Stanford University', 'University of Illinois--Urbana-Champaign', 'University of Washington', 'Princeton University', 'California Institute of Technology', 'Columbia University', 'University of Wisconsin--Madison', 'University of California--San Diego', 'University of Pennsylvania', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Cornell University', 'Georgia Institute of Technology', 'University of Texas--Austin', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Harvard University', 'University of Maryland--College Park', 'Purdue University--West Lafayette', 'California Institute of Technology', 'Stanford University', 'Columbia University', 'University of Texas--Austin', 'University of Arizona', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Arizona State University', 'University of California--San Diego', 'Cornell University', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Pennsylvania State University--University Park', 'Harvard University', 'Princeton University', 'University of Washington', 'Yale University', 'Brown University', 'University of Wisconsin--Madison', 'University of California--Santa Barbara', 'Princeton University', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Columbia University', 'California Institute of Technology', 'Yale University', 'Cornell University', 'University of Texas--Austin', 'University of Pennsylvania', 'University of California--San Diego', 'Harvard University', 'Stanford University', 'University of Chicago', 'University of California--Los Angeles', 'New York University', 'University of Michigan--Ann Arbor', 'Brown University', 'Duke University', 'University of Wisconsin--Madison', 'University of Illinois--Urbana-Champaign', 'Massachusetts Institute of Technology', 'California Institute of Technology', 'Princeton University', 'Cornell University', 'University of Illinois--Urbana-Champaign', 'University of California--Santa Barbara', 'University of Michigan--Ann Arbor', 'University of Maryland--College Park', 'Johns Hopkins University', 'University of California--San Diego', 'Stanford University', 'Harvard University', 'University of California--Berkeley', 'University of Chicago', 'Columbia University', 'Yale University', 'University of Colorado--Boulder', 'University of Pennsylvania', 'University of California--Los Angeles', 'University of Texas--Austin']

In [10]:
#Statistics

executable_path = {"executable_path": r"C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\chromedriver.exe"}
browser = Browser("chrome", **executable_path, headless=False)
url1 = "https://www.usnews.com/best-graduate-schools/top-science-schools/statistics-rankings"
browser.visit(url1)

time.sleep(80)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

j = 0


for i in soup.findAll('tr', attrs = {'class' : 'zebra TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
for i in soup.findAll('tr', attrs = {'class' : 'TableTabular__TableRow-s9v6iyg-1 PNbVY'}):
    
    time.sleep(1.5)
    
    target1 = i.find('p', attrs={'class' : 'Paragraph-fqygwe-0 fJtpNK'})
    target2 = i.find('strong', class_='s144f3me-0-Strong-kDSDFS eULIZs')
    target3 = i.find('h3', class_='sc-bdVaJa kyuLHz')
    
    universityName.append(target3.text)
    cities.append(target1.text)
    rankNumber.append(target2.text)
    
    j = j + 1

    print (f'Processing record {j} of 192.')
    
    if j == 50:
        break
        
print(cities)
print(rankNumber)
print(universityName)

Processing record 1 of 192.
Processing record 2 of 192.
Processing record 3 of 192.
Processing record 4 of 192.
Processing record 5 of 192.
Processing record 6 of 192.
Processing record 7 of 192.
Processing record 8 of 192.
Processing record 9 of 192.
Processing record 10 of 192.
Processing record 11 of 192.
Processing record 12 of 192.
Processing record 13 of 192.
Processing record 14 of 192.
Processing record 15 of 192.
Processing record 16 of 192.
Processing record 17 of 192.
Processing record 18 of 192.
Processing record 19 of 192.
Processing record 20 of 192.
['Cambridge, MA', 'Berkeley, CA', 'Boston, MA', 'Princeton, NJ', 'New Haven, CT', 'Durham, NC', 'New York, NY', 'St. Louis, MO', 'La Jolla, CA', 'Davis, CA', 'Stanford, CA', 'Pasadena, CA', 'Baltimore, MD', 'San Francisco, CA', 'Ithaca, NY', 'La Jolla, CA', 'Chicago, IL', 'Cold Spring Harbor, NY', 'New York, NY', 'Los Angeles, CA', 'Pasadena, CA', 'Cambridge, MA', 'Berkeley, CA', 'La Jolla, CA', 'New York, NY', 'Princeton, NJ', 'New Haven, CT', 'Los Angeles, CA', 'Chapel Hill, NC', 'Philadelphia, PA', 'Cambridge, MA', 'Stanford, CA', 'Evanston, IL', 'Urbana, IL', 'Ithaca, NY', 'Madison, WI', 'Chicago, IL', 'Ann Arbor, MI', 'Austin, TX', 'Atlanta, GA', 'Pittsburgh, PA', 'Stanford, CA', 'Urbana, IL', 'Seattle, WA', 'Princeton, NJ', 'Pasadena, CA', 'New York, NY', 'Madison, WI', 'La Jolla, CA', 'Philadelphia, PA', 'Cambridge, MA', 'Berkeley, CA', 'Ithaca, NY', 'Atlanta, GA', 'Austin, TX', 'Ann Arbor, MI', 'Los Angeles, CA', 'Cambridge, MA', 'College Park, MD', 'West Lafayette, IN', 'Pasadena, CA', 'Stanford, CA', 'Palisades, NY', 'Austin, TX', 'Tucson, AZ', 'Ann Arbor, MI', 'Los Angeles, CA', 'Tempe, AZ', 'La Jolla, CA', 'Ithaca, NY', 'Cambridge, MA', 'Berkeley, CA', 'University Park, PA', 'Cambridge, MA', 'Princeton, NJ', 'Seattle, WA', 'New Haven, CT', 'Providence, RI', 'Madison, WI', 'Santa Barbara, CA', 'Princeton, NJ', 'Cambridge, MA', 'Berkeley, CA', 'New York, NY', 'Pasadena, CA', 'New Haven, CT', 'Ithaca, NY', 'Austin, TX', 'Philadelphia, PA', 'La Jolla, CA', 'Cambridge, MA', 'Stanford, CA', 'Chicago, IL', 'Los Angeles, CA', 'New York, NY', 'Ann Arbor, MI', 'Providence, RI', 'Durham, NC', 'Madison, WI', 'Urbana, IL', 'Cambridge, MA', 'Pasadena, CA', 'Princeton, NJ', 'Ithaca, NY', 'Urbana, IL', 'Santa Barbara, CA', 'Ann Arbor, MI', 'College Park, MD', 'Baltimore, MD', 'La Jolla, CA', 'Stanford, CA', 'Cambridge, MA', 'Berkeley, CA', 'Chicago, IL', 'New York, NY', 'New Haven, CT', 'Boulder, CO', 'Philadelphia, PA', 'Los Angeles, CA', 'Austin, TX', 'Stanford, CA', 'Boston, MA', 'Seattle, WA', 'Chicago, IL', 'Chapel Hill, NC', 'Ann Arbor, MI', 'Berkeley, CA', 'Philadelphia, PA', 'Raleigh, NC', 'Chapel Hill, NC', 'Berkeley, CA', 'Baltimore, MD', 'Cambridge, MA', 'Pittsburgh, PA', 'Seattle, WA', 'Durham, NC', 'Ann Arbor, MI', 'New York, NY', 'Madison, WI', 'Ithaca, NY']
['#1 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#13 ', '#13 ', '#16 ', '#18 ', '#1 ', '#4 ', '#6 ', '#6 ', '#10 ', '#10 ', '#13 ', '#16 ', '#18 ', '#18 ', '#1 ', '#2 ', '#2 ', '#6 ', '#9 ', '#9 ', '#9 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#6 ', '#6 ', '#9 ', '#9 ', '#14 ', '#15 ', '#15 ', '#20 ', '#1 ', '#1 ', '#5 ', '#6 ', '#8 ', '#11 ', '#13 ', '#13 ', '#16 ', '#19 ', '#1 ', '#1 ', '#6 ', '#8 ', '#10 ', '#11 ', '#13 ', '#16 ', '#16 ', '#20 ', '#1 ', '#2 ', '#5 ', '#7 ', '#8 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ', '#2 ', '#2 ', '#5 ', '#8 ', '#10 ', '#10 ', '#13 ', '#15 ', '#15 ', '#19 ', '#1 ', '#2 ', '#2 ', '#7 ', '#9 ', '#9 ', '#13 ', '#14 ', '#16 ', '#19 ', '#2 ', '#2 ', '#6 ', '#7 ', '#9 ', '#12 ', '#14 ', '#16 ', '#16 ', '#19 ', '#1 ', '#3 ', '#3 ', '#7 ', '#9 ', '#10 ', '#13 ', '#14 ', '#17 ', '#17 ', '#1 ', '#3 ', '#3 ', '#7 ', '#10 ', '#12 ', '#14 ', '#14 ', '#17 ', '#17 ', '#1 ', '#3 ', '#3 ', '#6 ', '#8 ', '#11 ', '#12 ', '#12 ', '#16 ', '#19 ', '#2 ', '#3 ', '#6 ', '#8 ', '#8 ', '#12 ', '#12 ', '#16 ', '#16 ', '#20 ']
['Massachusetts Institute of Technology', 'University of California--Berkeley', 'Harvard University', 'Princeton University', 'Yale University', 'Duke University', 'Rockefeller University', 'Washington University in St. Louis', 'University of California--San Diego', 'University of California--Davis', 'Stanford University', 'California Institute of Technology', 'Johns Hopkins University', 'University of California--San Francisco', 'Cornell University', 'The Scripps Research Institute', 'University of Chicago', 'Cold Spring Harbor Laboratory', 'Columbia University', 'University of California--Los Angeles', 'California Institute of Technology', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'The Scripps Research Institute', 'Columbia University', 'Princeton University', 'Yale University', 'University of California--Los Angeles', 'University of North Carolina--Chapel Hill', 'University of Pennsylvania', 'Harvard University', 'Stanford University', 'Northwestern University', 'University of Illinois--Urbana-Champaign', 'Cornell University', 'University of Wisconsin--Madison', 'University of Chicago', 'University of Michigan--Ann Arbor', 'University of Texas--Austin', 'Georgia Institute of Technology', 'Carnegie Mellon University', 'Stanford University', 'University of Illinois--Urbana-Champaign', 'University of Washington', 'Princeton University', 'California Institute of Technology', 'Columbia University', 'University of Wisconsin--Madison', 'University of California--San Diego', 'University of Pennsylvania', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Cornell University', 'Georgia Institute of Technology', 'University of Texas--Austin', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Harvard University', 'University of Maryland--College Park', 'Purdue University--West Lafayette', 'California Institute of Technology', 'Stanford University', 'Columbia University', 'University of Texas--Austin', 'University of Arizona', 'University of Michigan--Ann Arbor', 'University of California--Los Angeles', 'Arizona State University', 'University of California--San Diego', 'Cornell University', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Pennsylvania State University--University Park', 'Harvard University', 'Princeton University', 'University of Washington', 'Yale University', 'Brown University', 'University of Wisconsin--Madison', 'University of California--Santa Barbara', 'Princeton University', 'Massachusetts Institute of Technology', 'University of California--Berkeley', 'Columbia University', 'California Institute of Technology', 'Yale University', 'Cornell University', 'University of Texas--Austin', 'University of Pennsylvania', 'University of California--San Diego', 'Harvard University', 'Stanford University', 'University of Chicago', 'University of California--Los Angeles', 'New York University', 'University of Michigan--Ann Arbor', 'Brown University', 'Duke University', 'University of Wisconsin--Madison', 'University of Illinois--Urbana-Champaign', 'Massachusetts Institute of Technology', 'California Institute of Technology', 'Princeton University', 'Cornell University', 'University of Illinois--Urbana-Champaign', 'University of California--Santa Barbara', 'University of Michigan--Ann Arbor', 'University of Maryland--College Park', 'Johns Hopkins University', 'University of California--San Diego', 'Stanford University', 'Harvard University', 'University of California--Berkeley', 'University of Chicago', 'Columbia University', 'Yale University', 'University of Colorado--Boulder', 'University of Pennsylvania', 'University of California--Los Angeles', 'University of Texas--Austin', 'Stanford University (Department of Statistics)', 'Harvard University (Department of Biostatistics)', 'University of Washington (Department of Biostatistics)', 'University of Chicago (Department of Statistics)', 'University of North Carolina--Chapel Hill (Department of Biostatistics)', 'University of Michigan--Ann Arbor (Department of Biostatistics)', 'University of California--Berkeley (Group in Biostatistics)', 'University of Pennsylvania (Department of Statistics)', 'North Carolina State University (Department of Statistics)', 'University of North Carolina--Chapel Hill (Department of Statistics & Operations Research)', 'University of California--Berkeley (Department of Statistics)', 'Johns Hopkins University (Department of Biostatistics)', 'Harvard University (Department of Statistics)', 'Carnegie Mellon University (Department of Statistics)', 'University of Washington (Department of Statistics)', 'Duke University (Department of Statistical Science)', 'University of Michigan--Ann Arbor (Department of Statistics)', 'Columbia University (Department of Statistics)', 'University of Wisconsin--Madison (Department of Statistics)', 'Cornell University (Department of Statistical Science)']

In [11]:
names = ('INSTNM', 'firstcity', 'Degree', 'Rank')
data = pd.DataFrame(columns = names)
data

Empty DataFrame
Columns: [INSTNM, firstcity, Degree, Rank]
Index: []

In [12]:
degrees = []

for i in range (20):
    degrees.append('Biological Sciences')

for i in range (20):
    degrees.append('Chemistry')
    
for i in range (20):
    degrees.append('Computer Sciences')

for i in range (20):
    degrees.append('Earth Sciences')
    
for i in range (20):
    degrees.append('Mathematics')

for i in range (20):
    degrees.append('Physics')
    
for i in range (20):
    degrees.append('Statistics')
    
degrees

['Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Biological Sciences',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Chemistry',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Computer Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Earth Sciences',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Mathematics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Physics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics',
 'Statistics']

In [13]:
data['INSTNM'] = universityName
data['firstcity'] = cities
data['Degree'] = degrees
data['Rank'] = rankNumber

data.head()

,INSTNM,firstcity,Degree,Rank
0,Massachusetts Institute of Technology,"Cambridge, MA",Biological Sciences,#1
1,University of California--Berkeley,"Berkeley, CA",Biological Sciences,#1
2,Harvard University,"Boston, MA",Biological Sciences,#4
3,Princeton University,"Princeton, NJ",Biological Sciences,#6
4,Yale University,"New Haven, CT",Biological Sciences,#6

In [14]:
data['Rank'] = data['Rank'].apply(str).replace('#', '', regex=True)

data.head()

,INSTNM,firstcity,Degree,Rank
0,Massachusetts Institute of Technology,"Cambridge, MA",Biological Sciences,1
1,University of California--Berkeley,"Berkeley, CA",Biological Sciences,1
2,Harvard University,"Boston, MA",Biological Sciences,4
3,Princeton University,"Princeton, NJ",Biological Sciences,6
4,Yale University,"New Haven, CT",Biological Sciences,6

In [15]:
data['CITY'] = data.firstcity.str.split(', ').str[0]
data['STATE'] = data.firstcity.str.split(', ').str[-1]

data

,INSTNM,firstcity,Degree,Rank,CITY,STATE
0,Massachusetts Institute of Technology,"Cambridge, MA",Biological Sciences,1,Cambridge,MA
1,University of California--Berkeley,"Berkeley, CA",Biological Sciences,1,Berkeley,CA
2,Harvard University,"Boston, MA",Biological Sciences,4,Boston,MA
3,Princeton University,"Princeton, NJ",Biological Sciences,6,Princeton,NJ
4,Yale University,"New Haven, CT",Biological Sciences,6,New Haven,CT
...,...,...,...,...,...,...
135,Duke University (Department of Statistical Sci...,"Durham, NC",Statistics,12,Durham,NC
136,University of Michigan--Ann Arbor (Department ...,"Ann Arbor, MI",Statistics,12,Ann Arbor,MI
137,Columbia University (Department of Statistics),"New York, NY",Statistics,16,New York,NY
138,University of Wisconsin--Madison (Department o...,"Madison, WI",Statistics,16,Madison,WI
139,Cornell University (Department of Statistical ...,"Ithaca, NY",Statistics,20,Ithaca,NY

In [16]:
data.to_csv(r'C:\Users\Gabriel\Desktop\Classes_ASU\U_of_A\Brute-Force-Grad-College-Rankings-Map\ScienceRankData.csv')